### PR TITLE
Remove unnecessary udev rules

### PR DESCRIPTION
**Pull request by gber**
Currently mtp-server does not work due to an invalid udev rule overwriting an UBports rule from lxc-android-config. There are numerous other redundant or incorrect rules.

The second commit comments out a bunch of rules with reasons given as inline comments. Marked as draft in order to discuss these and potentially identify even more.

### CODE REVIEW

**Comment by fredldotme** [comment]
The reason USB worked on xenial was because of the setupusb script setting up the permissions before mtp-server came to open it. No fan of it myself but I didn't expect it being copypasted all around the place. Good to know it doesn't trigger anymore.

In any case, if it fits we can certainly merge it as is, but thanks for waiting as Draft. I'd say let's just wait until the next stable release is out and merge it then. In the meantime I'm going to test it on my daily driver.

**Comment by gber** [comment]
> In any case, if it fits we can certainly merge it as is, but thanks for waiting as Draft. I'd say let's just wait until the next stable release is out and merge it then. In the meantime I'm going to test it on my daily driver.

I didn't originally intend to have it merged as-is, more to ease review/discussion of the changes. Should the rules remain commented out or rather removed? Should we split this up into multiple commits, maybe grouped somehow (e.g. by the reason why rules are removed)?

Also could you take a look that there are not any glaring mistakes in the removal of rules?  That's why I added a comments on top of each commented out rule.

Could you check whether more can be removed, I'm not too familiar with the phone/android-specific stuff and thus didn't touch that?

**Comment by fredldotme** [comment]
> > In any case, if it fits we can certainly merge it as is, but thanks for waiting as Draft. I'd say let's just wait until the next stable release is out and merge it then. In the meantime I'm going to test it on my daily driver.
> 
> I didn't originally intend to have it merged as-is, more to ease review/discussion of the changes. Should the rules remain commented out or rather removed? Should we split this up into multiple commits, maybe grouped somehow (e.g. by the reason why rules are removed)?
> 
> Also could you take a look that there are not any glaring mistakes in the removal of rules? That's why I added a comments on top of each commented out rule.
> 
> Could you check whether more can be removed, I'm not too familiar with the phone/android-specific stuff and thus didn't touch that?

I know it's still a draft out of a multitude of reasons, hence me saying "if it fits" ;)
Anyway, I will do some regression testing first, will let you know asap how it's going.
But yeah, having the comments removed might make it look cleaner.

**Comment by fredldotme** [comment]
Thought about the verbosity and I'm actually totally fine with that.
I actually like that it tells exactly what and why it differs from the source uevent.rc.
So for all I care about you're free to mark it as ready.

**Comment by gber** [comment]
OK, I've cleaned this up a bit.

**Comment by fredldotme** [comment]
Thanks, merged!

**Pull request merged**
